# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/miniai',
                'doc_host': 'https://ruxandra2ichim.github.io',
                'git_url': 'https://github.com/ruxandra2ichim/miniai',
                'lib_path': 'miniai'},
  'syms': { 'miniai.core': {'miniai.core.foo': ('core.html#foo', 'miniai/core.py')},
            'miniai.datasets': { 'miniai.datasets.DataLoaders': ('datasets.html#dataloaders', 'miniai/datasets.py'),
                                 'miniai.datasets.DataLoaders.__init__': ('datasets.html#dataloaders.__init__', 'miniai/datasets.py'),
                                 'miniai.datasets.DataLoaders.from_dd': ('datasets.html#dataloaders.from_dd', 'miniai/datasets.py'),
                                 'miniai.datasets.collate_dict': ('datasets.html#collate_dict', 'miniai/datasets.py'),
                                 'miniai.datasets.get_dls': ('datasets.html#get_dls', 'miniai/datasets.py'),
                                 'miniai.datasets.get_grid': ('datasets.html#get_grid', 'miniai/datasets.py'),
                                 'miniai.datasets.inplace': ('datasets.html#inplace', 'miniai/datasets.py'),
                                 'miniai.datasets.show_image': ('datasets.html#show_image', 'miniai/datasets.py'),
                                 'miniai.datasets.show_images': ('datasets.html#show_images', 'miniai/datasets.py'),
                                 'miniai.datasets.subplots': ('datasets.html#subplots', 'miniai/datasets.py')},
            'miniai.hello': {'miniai.hello.say_hello': ('hello.html#say_hello', 'miniai/hello.py')}}}
