# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/miniai',
                'doc_host': 'https://ruxandra2ichim.github.io',
                'git_url': 'https://github.com/ruxandra2ichim/miniai',
                'lib_path': 'miniai'},
  'syms': {'miniai.core': {'miniai.core.foo': ('core.html#foo', 'miniai/core.py')}}}
