# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_hello.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../nbs/01_hello.ipynb 3
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
