name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    # steps: [uses: fastai/workflows/quarto-ghp@master]
    # steps: [uses: actions/quarto-ghp@master]
    steps:
    - uses: actions/checkout@main
      name: Checkout
    - uses: ./.github/actions/quarto-ci
      name: Test
