name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    # steps: [uses: fastai/workflows/nbdev-ci@master]
    # steps: [uses: actions/nbdev-ci@master]
    steps:
    - uses: actions/checkout@v4
      name: Checkout
    - uses: ./.github/actions/nbdev-ci
      name: Test
